### ISSUE TITLE
watch in block explorer link does nothing

### ISSUE THREAD

**Issue by divine-comedian** [EVMcrispr/evmcrispr#32]
testing on `https://evm-crispr.blossom.software/#/terminal`
brave shields are OFF

I attempt to forward a script, it fails. 
I receive the failed tx message from metamask and at the bottom of the evmcrispr terminal there is a button that says `watch in block explorer` and provides the tx hash, clicking this does nothing..

![image](https://user-images.githubusercontent.com/67759413/171725855-4c3302f2-cccc-4ef0-8936-d6152b86b24b.png)

the failed tx hash can be found here:
https://blockscout.com/xdai/mainnet/tx/0xbd2307992f423d27fe3df146258e9b0e5b0fa0ad739e2eb75a4f6fbe5b5d0329

**Comment by sembrestels** [comment]
In later versions of EVMcrispr this message do not appear anymore. Maybe in the future we show both executed and failed transactions with links in the print modal. For now I close this issue.
