### ISSUE TITLE
Can't create new-dao on Mumbai/Polygon

### ISSUE THREAD

**Issue by devmerit** [EVMcrispr/evmcrispr#46]
When trying to create new dao in terminal on any networks other than Mainnet or Gnosis:

```
load aragonos as ar
ar:new-dao mynewblankdaozero
```

I get:

> ar:new-dao(33:0,33:28): invalid contract address or ENS name (argument="addressOrName", value=null, code=INVALID_ARGUMENT, version=contracts/5.7.0)

Already added all aragon environments on Mumbai/Polygon to `evmcrispr/packages/evmcrispr/src/modules/aragonos/utils/factories.ts` and `evmcrispr/packages/evmcrispr/src/modules/aragonos/utils/resolvers.ts` -- no effect.

`New-token` on Mumbai works fine. Using Metamask/Firefox.

**Comment by sembrestels** [comment]
Sorry, we could never give good support for Aragon on Polygon since not all Aragon smart contracts were deployed there. Support for Aragon in polygon is completely removed after the sunset of the graph hosted service.
