### ISSUE TITLE
Support radspec descriptions

### ISSUE THREAD

**Issue by 0xGabi** [EVMcrispr/evmcrispr#5]
Use radspec to describe votes. We should include the latest changes to the radspec library that:
- Refactor it to use ethers library: https://github.com/1Hive/radspec/pull/1
- Include a new feature that allows customizing the list of known function signatures: https://github.com/1Hive/radspec/pull/2. This new feature we can uplift to the EVMcripr init options.

**Comment by sembrestels** [comment]
EVMcrispr is not focused on AragonOS anymore, so most of the contracts it interacts with wouldn't have radspec descriptions. I don't think we should integrate this functionality.
